[project]
name = "lern-celery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "celery>=5.5.2",
    "django>=5.2.1",
    "redis>=6.1.0",
]
